
rem lab23.sql
SELECT  MODEL_NO, MODEL_NAME,YEAR_START,YEAR_FINISH,SERVICE_INTERVAL		    		
	FROM MODEL;


SELECT IG_MIN,IG_MAX,MODEL_NAME,DERIV_NAME
FROM MODEL,DERIVATIVE
WHERE MODEL.MODEL_NO = DERIVATIVE.MODEL_NO
AND DERIVATIVE.IG_MIN >= 6
AND DERIVATIVE.IG_MAX > 6
AND DERIVATIVE.AUTO = 'N';


SELECT TRADE FROM YEAR_PRICE, DERIVATIVE
WHERE YEAR_PRICE.DERIV_NO = DERIVATIVE.DERIV_NO
AND YEAR_PRICE.YEAR = 2003
AND YEAR_PRICE.REGI = '53'
AND DERIVATIVE.DERIV_NAME = 'Quattro'
AND DERIVATIVE.BODY = 'Saloon';
